-- SCOTT.TB_USER definition

CREATE TABLE "SCOTT"."TB_USER" 
   (	"USER_NO" VARCHAR2(20), 
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"USER_PWD" VARCHAR2(20) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"USER_PHONE" VARCHAR2(15) NOT NULL ENABLE, 
	"USER_BIRTH" DATE, 
	"USER_ZIPCODE" VARCHAR2(10) NOT NULL ENABLE, 
	"USER_ADDR" VARCHAR2(100) NOT NULL ENABLE, 
	"USER_DETAIL_ADDR" VARCHAR2(100) NOT NULL ENABLE, 
	"USER_REG_DATE" DATE NOT NULL ENABLE, 
	"EXIT_STATUS" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"EXIT_DATE" DATE, 
	"ACCOUNT_STATUS" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"FAIL_CNT" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	"IS_MANAGER" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"LOGIN_TIME" DATE, 
	 PRIMARY KEY ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "SCOTT"."SYS_C008600" ON "SCOTT"."TB_USER" ("USER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "SCOTT"."SYS_C008601" ON "SCOTT"."TB_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  -- SCOTT.TB_USER_EDIT_RECORD definition

CREATE TABLE "SCOTT"."TB_USER_EDIT_RECORD" 
   (	"EDIT_NO" VARCHAR2(20), 
	"USER_NO" VARCHAR2(20) NOT NULL ENABLE, 
	"EDIT_PWD" VARCHAR2(20) NOT NULL ENABLE, 
	"EDIT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"EDIT_PHONE" VARCHAR2(15) NOT NULL ENABLE, 
	"EDIT_BIRTH" DATE, 
	"EDIT_ZIPCODE" VARCHAR2(10) NOT NULL ENABLE, 
	"EDIT_ADDR" VARCHAR2(100) NOT NULL ENABLE, 
	"EDIT_DETAIL_ADDR" VARCHAR2(100) NOT NULL ENABLE, 
	"EDIT_REG_DATE" DATE NOT NULL ENABLE, 
	"EDIT_EXIT_STATUS" CHAR(1) NOT NULL ENABLE, 
	"EDIT_EXIT_DATE" DATE, 
	"EDIT_ACCOUNT_STATUS" CHAR(1) NOT NULL ENABLE, 
	"EDIT_MOD_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"IS_MANAGER" CHAR(1) NOT NULL ENABLE, 
	 PRIMARY KEY ("EDIT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_USER_EDIT_USER" FOREIGN KEY ("USER_NO")
	  REFERENCES "SCOTT"."TB_USER" ("USER_NO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "SCOTT"."SYS_C008614" ON "SCOTT"."TB_USER_EDIT_RECORD" ("EDIT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;

  -- SCOTT.TB_BOARD_TYPE definition

CREATE TABLE "SCOTT"."TB_BOARD_TYPE" 
   (	"BOARD_NO" VARCHAR2(20), 
	"BOARD_NAME" VARCHAR2(20), 
	 PRIMARY KEY ("BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("BOARD_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "SCOTT"."SYS_C008576" ON "SCOTT"."TB_BOARD_TYPE" ("BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "SCOTT"."SYS_C008577" ON "SCOTT"."TB_BOARD_TYPE" ("BOARD_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  -- SCOTT.TB_POST definition

CREATE TABLE "SCOTT"."TB_POST" 
   (	"POST_NO" VARCHAR2(20), 
	"USER_NO" VARCHAR2(20) NOT NULL ENABLE, 
	"BOARD_NO" VARCHAR2(20) NOT NULL ENABLE, 
	"POST_TITLE" VARCHAR2(50) NOT NULL ENABLE, 
	"POST_CONTENT" VARCHAR2(350), 
	"COMMENT_STATUS" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"POST_REG_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"POST_MOD_DATE" DATE, 
	"IS_POST_DELETE" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"POST_DELETE_DATE" DATE, 
	"VIEW_CNT" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
	 PRIMARY KEY ("POST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_POST_USER" FOREIGN KEY ("USER_NO")
	  REFERENCES "SCOTT"."TB_USER" ("USER_NO") ENABLE, 
	 CONSTRAINT "FK_POST_BOARD" FOREIGN KEY ("BOARD_NO")
	  REFERENCES "SCOTT"."TB_BOARD_TYPE" ("BOARD_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "SCOTT"."SYS_C008623" ON "SCOTT"."TB_POST" ("POST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;